version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: si_community
      MYSQL_USER: test
      MYSQL_PASSWORD: test1234
    ports:
      - "13306:3306"
