version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: si_community
      MYSQL_USER: test
      MYSQL_PASSWORD: test1234
    ports:
      - "13306:3306"
    command: [ "--init-file", "/docker-entrypoint-initdb.d/init.sql" ]
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - host_network

networks:
  host_network:
    external: true
