basePath: /v1
definitions:
  models.UserResponseDto:
    properties:
      company:
        type: string
      email:
        type: string
      expiration_time:
        type: string
      nickname:
        type: string
      register_number:
        type: integer
      token:
        type: string
      token_id:
        type: integer
    type: object
host: localhost:8000
info:
  contact: {}
  description: This is a sample Gin API with Swagger documentation.
  title: Your Gin API
  version: "1.0"
paths:
  /v1/users:
    post:
      consumes:
      - application/json
      description: 자세한 설명은 이곳에 적습니다.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserResponseDto'
swagger: "2.0"
