basePath: /v1
definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.UserRequestDto:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.UserResponseDto:
    properties:
      company:
        type: string
      email:
        type: string
      expiration_time:
        type: string
      nickname:
        type: string
      register_number:
        type: integer
      token:
        type: string
      token_id:
        type: integer
    type: object
  models.Users:
    properties:
      company:
        type: string
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      email:
        type: string
      id:
        type: integer
      is_active:
        type: string
      loggedin:
        type: string
      nickname:
        type: string
      password:
        type: string
      register_number:
        type: integer
      updatedAt:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: This is a sample Gin API with Swagger documentation.
  title: Your Gin API
  version: "1.0"
paths:
  /v1/users:
    post:
      consumes:
      - application/json
      description: 회원 가입
      parameters:
      - description: email, password, nickname, company만 있으면 됨
        in: body
        name: users
        schema:
          $ref: '#/definitions/models.Users'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Users'
  /v1/users/changePassword:
    post:
      consumes:
      - application/json
      description: 비밀번호 변경
      parameters:
      - description: 비밀번호 변경 input
        in: body
        name: users
        required: true
        schema:
          $ref: '#/definitions/models.UserRequestDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.UserResponseDto'
  /v1/users/signin:
    post:
      consumes:
      - application/json
      description: 로그인
      parameters:
      - description: 로그인 input
        in: body
        name: users
        required: true
        schema:
          $ref: '#/definitions/models.UserRequestDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.UserResponseDto'
swagger: "2.0"
